FILE(GLOB MODEL_VIEWER_SOURCE_FILES ${CMAKE_CURRENT_SOURCE_DIR}/*.cpp)
FILE(GLOB MODEL_VIEWER_HEADER_FILES ${CMAKE_CURRENT_SOURCE_DIR}/*.h)

ADD_EXECUTABLE(ModelViewer ${MODEL_VIEWER_SOURCE_FILES} ${MODEL_VIEWER_HEADER_FILES})
TARGET_LINK_LIBRARIES(ModelViewer PRIVATE glCommon gl-sample-common-asset-importer)
ADD_DEPENDENCIES(ModelViewer glCommon gl-sample-common-asset-importer)

TARGET_INCLUDE_DIRECTORIES(ModelViewer PRIVATE ${CMAKE_CURRENT_SOURCE_DIR})

INSTALL(TARGETS ModelViewer DESTINATION bin)