FILE(GLOB MORPH_TARGET_SOURCE_FILES ${CMAKE_CURRENT_SOURCE_DIR}/*.cpp)
FILE(GLOB MORPH_TARGET_HEADER_FILES ${CMAKE_CURRENT_SOURCE_DIR}/*.h)

ADD_EXECUTABLE(MorphTarget ${MORPH_TARGET_SOURCE_FILES} ${MORPH_TARGET_HEADER_FILES})
TARGET_LINK_LIBRARIES(MorphTarget glCommon gl-sample-common-asset-importer)
ADD_DEPENDENCIES(MorphTarget glCommon gl-sample-common-asset-importer)

TARGET_INCLUDE_DIRECTORIES(MorphTarget PRIVATE ${CMAKE_CURRENT_SOURCE_DIR})

INSTALL(TARGETS MorphTarget DESTINATION bin)