#version 460 core

layout(local_size_x = 16, local_size_y = 16, local_size_z = 1) in;

layout(set = 0, binding = 0, std430) readonly buffer Histogram { int histogram[]; }
histogram;

layout(binding = 1, rgba8) uniform restrict writeonly image2D renderTexture;

void main() {

	/*  */
	if (any(greaterThan(gl_GlobalInvocationID.xy, imageSize(renderTexture)))) {
		return;
	}

	const ivec2 texelCoords = ivec2(gl_GlobalInvocationID.xy);

	const ivec2 rt = imageSize(renderTexture);

	const uint histogram_index = texelCoords.x * rt.x + texelCoords.y;

	const float red = histogram.histogram[histogram_index];
	const float green = histogram.histogram[histogram_index];
	const float blue = histogram.histogram[histogram_index];

	imageStore(renderTexture, texelCoords, vec4(1, 1, 1, 1));
}