FILE(GLOB SOURCE_WIND_COEFF_FILES ${CMAKE_CURRENT_SOURCE_DIR}/*.cpp)
FILE(GLOB HEADER_WIND_COEFF_FILES ${CMAKE_CURRENT_SOURCE_DIR}/*.h)

# Terrain
ADD_EXECUTABLE(WindCoeff ${SOURCE_WIND_COEFF_FILES} ${HEADER_WIND_COEFF_FILES})
TARGET_LINK_LIBRARIES(WindCoeff glCommon gl-sample-common-asset-importer)
TARGET_INCLUDE_DIRECTORIES(WindCoeff PRIVATE ${CMAKE_CURRENT_SOURCE_DIR})
ADD_DEPENDENCIES(WindCoeff glCommon gl-sample-common-asset-importer)

INSTALL(TARGETS WindCoeff DESTINATION bin)