#version 460
#extension GL_ARB_separate_shader_objects : enable
#extension GL_ARB_compute_shader : enable
#extension GL_EXT_control_flow_attributes : enable

#extension GL_ARB_shading_language_include : enable

#extension GL_KHR_shader_subgroup_basic : enable
#extension GL_KHR_shader_subgroup_arithmetic : enable

precision mediump float;
precision mediump int;

layout(local_size_x = 16, local_size_y = 16, local_size_z = 1) in;

#include "common.glsl"
#include "compute.glsl"

layout(set = 0, binding = 0) uniform sampler2D ColorTexture;
layout(set = 0, binding = 1) uniform sampler2D DepthTexture;

/*	*/
layout(binding = 0, std140) uniform UniformBufferBlock {
	mat4 model;
	mat4 view;
	mat4 proj;
	mat4 modelView;
	mat4 ViewProj;
	mat4 modelViewProjection;
	/*	*/
	Camera camera;
	/*	*/
	vec4 center;
	vec4 size;
	vec4 padding;
}
ubo;

struct Result {
	float area;
	float averageNormal;
	vec3 averagePosition;
};

/*	*/
layout(std430, set = 0, binding = 2) writeonly buffer ResultBuffer { Result[] results; }
result;

layout(push_constant) uniform Transformation { layout(offset = 0) mat4 model; }
transform;

#if defined(GL_SUBGROUP_FEATURE_BASIC_BIT_KHR) && defined(GL_SUBGROUP_FEATURE_BASIC_BIT_KHR)

layout(constant_id = 2) const int sumSubGroupSize = 32;
shared float sat[sumSubGroupSize];
shared float sat0[sumSubGroupSize];
#else

layout(constant_id = 2) const int sumSubGroupSize = 16 * 16;

shared float[sumSubGroupSize] localBuff0;
shared float[sumSubGroupSize] localBuff1;
shared vec3[sumSubGroupSize] localBuff2;

#endif

float reduction(float[sumSubGroupSize] arr) {
	float m = 0;
	for (uint i = 0; i < arr.length(); i++) {
		m += arr[i];
	}
	return m;
}

vec3 reduction(vec3[sumSubGroupSize] arr) {
	vec3 m = vec3(0);
	for (uint i = 0; i < arr.length(); i++) {
		m += arr[i];
	}
	return m;
}

vec3 calcViewPosition(const in vec2 coords) {
	const float fragmentDepth = texture(DepthTexture, coords).r;

	return calcViewPosition(coords, inverse(ubo.proj), fragmentDepth);
}

void main() {

	const uint id = gl_LocalInvocationIndex;
	const uint work_index = getWorkIndex();

	/*	Reset Values.	 */
	{
		localBuff1[id] = 0;
		localBuff0[id] = 0;
		localBuff2[id] = vec3(0);
	}
	memoryBarrierShared();

	/*	*/
	const uvec2 color_texture_size = uvec2(textureSize(ColorTexture, 0));
	if (any(greaterThanEqual(gl_GlobalInvocationID.xy, color_texture_size))) {
		return;
	}

	const vec3 orth_normal = normalize(ubo.camera.viewDir.xyz);

	const vec2 texelSize = 1.0 / vec2(color_texture_size);
	const vec2 UVCoordinate = vec2(gl_GlobalInvocationID.xy) * texelSize;

	const vec3 normal = normalize(texture(ColorTexture, UVCoordinate)).xyz;
	const float depth = texture(DepthTexture, UVCoordinate).r;
	const float visable_area = float(depth < 1);

	/*	Determine front or back face.	*/
	const float visible_normal_surface_attenuation = dot(-orth_normal, normal.xyz);

	const vec3 viewPos = calcViewPosition(UVCoordinate);
	const vec3 position = viewPos.xyz;

#if defined(GL_SUBGROUP_FEATURE_BASIC_BIT_KHR) && defined(GL_SUBGROUP_FEATURE_BASIC_BIT_KHR)

	float triangle_visable_area = subgroupAdd(visable_area);
	float average_drag = subgroupAdd(visible_normal_surface_attenuation);
	vec3 average_position = subgroupAdd(position);

	/*	Merge all result.	*/
	if (gl_SubgroupInvocationID == 0) {
		/*	Sum over the subgroup.	*/
		localBuff0[gl_SubgroupID] = triangle_visable_area;
		localBuff1[gl_SubgroupID] = average_drag;
		localBuff2[gl_SubgroupID] = average_position;
	}

	memoryBarrierShared();

	barrier();

	float sum0 = 0;
	float average_drag0 = 0;
	vec3 average_drag0 = vec3(0);

	/*	*/
	if (gl_SubgroupID == 0) { /*	same as subgroupElect, possibly.	*/

		sum0 = gl_SubgroupInvocationID < gl_NumSubgroups ? localBuff0[gl_SubgroupInvocationID] : 0;
		sum0 = subgroupAdd(sum0);

		average_drag0 = gl_SubgroupInvocationID < gl_NumSubgroups ? localBuff1[gl_SubgroupInvocationID] : 0;
		average_drag0 = subgroupAdd(average_drag);

		average_position0 = gl_SubgroupInvocationID < gl_NumSubgroups ? localBuff2[gl_SubgroupInvocationID] : 0;
		average_position0 = subgroupAdd(average_position);
	}

	/*	*/
	if (gl_LocalInvocationID.x == 0) { /*	*/
		result.results[work_index].area = sum0;
		result.results[work_index].averageNormal = average_drag0;
		result.results[work_index].averagePosition = average_position0;
	}

#else
 
	/*	*/
	localBuff0[id] = visable_area;
	localBuff1[id] = visible_normal_surface_attenuation;
	localBuff2[id] = (position - ubo.center.xyz) * visable_area;

	memoryBarrierShared();

	barrier(); /*	*/

	if (id == 0) {

		/*	*/
		const float sumArea = reduction(localBuff0);
		const float sumNormalCos = reduction(localBuff1);
		const vec3 sumPosition = reduction(localBuff2);

		/*	*/
		result.results[work_index].area = sumArea;
		result.results[work_index].averageNormal = sumNormalCos;
		result.results[work_index].averagePosition = sumPosition;
	}

#endif
}
