#version 460
#extension GL_ARB_separate_shader_objects : enable
#extension GL_ARB_compute_shader : enable
#extension GL_EXT_control_flow_attributes : enable

precision mediump float;
precision mediump int;

layout(local_size_x = 32, local_size_y = 32, local_size_z = 1) in;

layout(set = 0, binding = 0) uniform sampler2D ColorTexture;

/*	*/
layout(std430, set = 0, binding = 3) writeonly buffer Result {
	layout(offset = 0) float area;
	layout(offset = 4) float averageNormal;
}
result;


layout(push_constant) uniform Transformation { layout(offset = 0) mat4 model; }
transform;

void main(){

}