FILE(GLOB SCENE_SOURCE_IMPORTER_FILES ${CMAKE_CURRENT_SOURCE_DIR}/*.cpp)
FILE(GLOB SCENE_HEADER_IMPORTER_FILES ${CMAKE_CURRENT_SOURCE_DIR}/*.h)

ADD_LIBRARY(gl-sample-common-scene ${SCENE_SOURCE_IMPORTER_FILES} ${SCENE_HEADER_IMPORTER_FILES})
TARGET_LINK_LIBRARIES(gl-sample-common-scene PUBLIC glCommon assimp gl-sample-common-asset-importer)

TARGET_INCLUDE_DIRECTORIES(gl-sample-common-scene PUBLIC
	${CMAKE_CURRENT_SOURCE_DIR}
)

INSTALL(TARGETS gl-sample-common-scene DESTINATION lib)
