#version 460
#extension GL_ARB_separate_shader_objects : enable
#extension GL_ARB_compute_shader : enable
#extension GL_EXT_control_flow_attributes : enable
#extension GL_GOOGLE_include_directive : enable

layout(local_size_x = 4, local_size_y = 4, local_size_z = 1) in;

#include "common.glsl"
#include "frustum.glsl"
// Input data

layout(set = 0, binding = 0, std140) uniform UniformBufferBlock {
	mat4 model;
	mat4 view;
	mat4 proj;
	mat4 modelView;
	mat4 modelViewProjection;
	HyperPlane planes[6];
}
ubo;

// TODO: determine if storage or uniform.
layout(set = 0, binding = 1, std140) uniform UniformInstanceBlock { AABB model[1024]; }
instance_ubo;
 

/*  output data.    */
layout(set = 0, binding = 2) buffer NumInstances { DrawElementsIndirectCommand indirect[]; };

int intersectionAABB(const in vec3 min, in const vec3 max) { return 0; }

void main() {
	const ivec2 pixel_coords = ivec2(gl_GlobalInvocationID.xy);
	const int nrPlanes = 6;

	[[unroll]] for (uint i = 0; i < nrPlanes; i++) {

		// if (intersectionAABB(vec3(0), vec3(0)) == 0) {
		// 	// Assign
		// 	// Atomic
		// }
	}
}