#version 460 core
#extension GL_ARB_separate_shader_objects : enable
#extension GL_ARB_compute_shader : enable
#extension GL_EXT_control_flow_attributes : enable
#extension GL_ARB_shading_language_include : enable
#extension GL_GOOGLE_include_directive : enable

layout(local_size_x = 128, local_size_y = 1, local_size_z = 1) in;

#include "scene.glsl"

struct mesh_reference{
    uint vertex_offset;
    uint indice_offset;
    uint indices_count;
};

struct entityData {
    AABB aabb;
    uint mesh_reference_index;
    uint material_reference_index;
};



void main()
{
	 
}
