FILE(GLOB SOURCE_FOREST_TERRAIN_FILES ${CMAKE_CURRENT_SOURCE_DIR}/*.cpp)
FILE(GLOB HEADER_FOREST_TERRAIN_FILES ${CMAKE_CURRENT_SOURCE_DIR}/*.h)

# Terrain Forest
ADD_EXECUTABLE(ForestTerrain ${SOURCE_FOREST_TERRAIN_FILES} ${HEADER_FOREST_TERRAIN_FILES})
TARGET_LINK_LIBRARIES(ForestTerrain glCommon gl-sample-common-asset-importer)
TARGET_INCLUDE_DIRECTORIES(ForestTerrain PRIVATE ${CMAKE_CURRENT_SOURCE_DIR})
ADD_DEPENDENCIES(ForestTerrain glCommon gl-sample-common-asset-importer)

INSTALL(TARGETS ForestTerrain DESTINATION bin)
