FILE(GLOB MODEL_BASE_SOURCE_FILES ${CMAKE_CURRENT_SOURCE_DIR}/*.cpp)
FILE(GLOB MODEL_BASE_HEADER_FILES ${CMAKE_CURRENT_SOURCE_DIR}/*.h)

ADD_EXECUTABLE(ModelBase ${MODEL_BASE_SOURCE_FILES} ${MODEL_BASE_HEADER_FILES} )
TARGET_LINK_LIBRARIES(ModelBase glCommon gl-sample-common-asset-importer)
ADD_DEPENDENCIES(ModelBase glCommon gl-sample-common-asset-importer)

TARGET_INCLUDE_DIRECTORIES(ModelBase PRIVATE ${CMAKE_CURRENT_SOURCE_DIR} )

INSTALL(TARGETS ModelBase DESTINATION bin)

# Library component
ADD_LIBRARY(ModelViewer-Core ${CMAKE_CURRENT_SOURCE_DIR}/ModelBase.cpp ${MODEL_VIEWER_HEADER_FILES})
TARGET_LINK_LIBRARIES(ModelViewer-Core PUBLIC glCommon gl-sample-common-asset-importer)
TARGET_INCLUDE_DIRECTORIES(ModelViewer-Core PUBLIC ${CMAKE_CURRENT_SOURCE_DIR} )
ADD_DEPENDENCIES(ModelViewer-Core glCommon gl-sample-common-asset-importer)
INSTALL(TARGETS ModelViewer-Core DESTINATION lib)