#version 460 core
#extension GL_ARB_shading_language_include : enable
#extension GL_GOOGLE_include_directive : enable

layout(local_size_x = 16, local_size_y = 16, local_size_z = 1) in;

layout(set = 0, binding = 0) uniform samplerCube SourceTexture;
layout(set = 0, binding = 1, rgba16f) uniform writeonly image2D TargetTexture;

#include "common.glsl"

void main() {

	/*  */
	if (any(greaterThan(gl_GlobalInvocationID.xy, imageSize(TargetTexture).xy))) {
		return;
	}

	/*	Get pixel coordinate.	*/
	const ivec2 pixel_coords = ivec2(gl_GlobalInvocationID.xy);
	const vec2 normalized_uv_coords = vec2(pixel_coords) / imageSize(TargetTexture).xy;
	const vec2 shifted_uv = 2.0 * vec2(normalized_uv_coords.x, 1.0 - normalized_uv_coords.y) - vec2(1.0);
	const vec3 direction = equirectangular(shifted_uv);

	const vec4 source_texture_color = texture(SourceTexture, direction);

	imageStore(TargetTexture, pixel_coords, source_texture_color);
}