#version 460 core
layout(local_size_x = 16, local_size_y = 16, local_size_z = 1) in;

layout(set = 0, binding = 0, std430) buffer SSBO {
	int histogram[]; // This array can now be tightly packed.
};

layout(binding = 0, r8ui) uniform readonly uimage2D image;

layout(binding = 1) uniform sampler2D sTexture;

void main() {

	/*	*/
	if (any(greaterThan(gl_GlobalInvocationID.xy, imageSize(image)))) {
		return;
	}

	const ivec2 texelCoords = ivec2(gl_GlobalInvocationID.xy);

	const ivec2 rt = textureSize(sTexture, 0);

	if (texelCoords.x < rt.x && texelCoords.y < rt.y) {
		const vec4 color = texelFetch(sTexture, texelCoords, 0);

		int gray = int(255.0 * (0.299 * color.r + 0.587 * color.g + 0.114 * color.b));

		gray = clamp(gray, 0, 255);

		atomicAdd(histogram[gray], 1);
	}
}