FILE(GLOB SOURCE_TERRAIN_FILES ${CMAKE_CURRENT_SOURCE_DIR}/*.cpp)
FILE(GLOB HEADER_TERRAIN_FILES ${CMAKE_CURRENT_SOURCE_DIR}/*.h)

# Planet
ADD_EXECUTABLE(Planet ${SOURCE_TERRAIN_FILES} ${HEADER_TERRAIN_FILES})
TARGET_LINK_LIBRARIES(Planet glCommon gl-sample-common-asset-importer)
TARGET_INCLUDE_DIRECTORIES(Planet PRIVATE ${CMAKE_CURRENT_SOURCE_DIR})
ADD_DEPENDENCIES(Planet glCommon gl-sample-common-asset-importer)

INSTALL(TARGETS Planet DESTINATION bin)